import { checkEnv } from "./utils/env-checker.js";

// Required envs for Podcast-MP3
checkEnv([
  "BUCKET_MERGED",
  "GCP_PROJECT_ID",
  "GOOGLE_APPLICATION_CREDENTIALS",
  "MIN_INTRO_DURATION",
  "MIN_OUTRO_DURATION",
  "PODCAST_INTRO_URL",
  "PODCAST_OUTRO_URL",
  "PORT",
  "PROCESSING_TIMEOUT_MS",
  "R2_BUCKET_PODCAST",
  "R2_BUCKET_RAW",
  "R2_BUCKET_RAW_TEXT",
  "R2_META_BUCKET",
  "R2_PUBLIC_BASE_URL_MERGE",
  "R2_PUBLIC_BASE_URL_META",
  "R2_PUBLIC_BASE_URL_PODCAST",
  "R2_PUBLIC_BASE_URL_RAW",
  "R2_PUBLIC_BASE_URL_RAW_TEXT",
  "NODE_ENV",
  "LOG_LEVEL"
]);

console.log("🚀 Podcast-MP3 service running...");
